version: '3.8'

services:
  wp-traffic-generator:
    build: .
    container_name: wp_traffic_generator
    environment:
      - WP_URL=http://winznlabapp
      - WP_USER=admin
      - WP_PASSWORD=mujkomplic84$
      - TRAFFIC_INTERVAL=60
      - POST_INTERVAL=300
    restart: unless-stopped

